### ISSUE TITLE
Encoder Support

### ISSUE THREAD

**Issue by nitej** [sensille/litehm2#1]
What changes would be needed to add support for encoders through the rv901t board? Is it just modifications to the hostmot2.py file?

**Comment by sensille** [comment]
I pushed a commit that adds qcounter support and build a new bitstream. I can't test it right now as I don't have a spare board, but I ordered one.
Please let me know if that is what you had in mind.

**Comment by nitej** [comment]
Yes, this is exactly what I had in mind. I am also waiting on a board to arrive to test it. Thank you for adding encoder support.
