### ISSUE TITLE
Initial Flash Size Difference

### ISSUE THREAD

**Issue by nitej** [sensille/litehm2#2]
The .bin flash file in the bitstream directory appears to be smaller than what flashrom is expecting for the flash chip on the RV901T board (which has a 32Mb flash chip). Does the file in the bitstream folder need to be padded out?

**Comment by sensille** [comment]
You are right, it needs to be padded. I added a padded version of litehm2.bin as bitstreams/initial.bin.

**Comment by sensille** [comment]
Close as answered
