### ISSUE TITLE
riscv toolchain

### ISSUE THREAD

**Issue by tuxcnc** [sensille/litehm2#3]
I tried compile litehm2 on fresh Linux installation and got rather info not error : 

`OSError: Unable to find any of the cross compilation toolchains:
- riscv64-pc-linux-musl
- riscv64-unknown-elf
- riscv64-unknown-linux-gnu
- riscv64-elf
- riscv64-linux
- riscv64-linux-gnu
- riscv-sifive-elf
- riscv64-none-elf
- riscv32-unknown-elf
- riscv32-unknown-linux-gnu
- riscv32-elf
- riscv-none-embed
- riscv-none-elf
`
Which one should I install ?

**Comment by sensille** [comment]
litex documentation says ./litex_setup.py --gcc=riscv.

I have riscv64-linux-gnu-gcc 12.2.0-1 installed.
